### ISSUE TITLE
Bug - Problem with spaces in autoscaling group

### ISSUE THREAD

**Issue by thomaspeitz** [MonsantoCo/etcd-aws-cluster#18]
Hey Ho,

first - Thanks for your awesome script. It works like a charm :)
Just found a small bug regarding Autoscaling Group Names with spaces in the name.
Its fixed if you use quotes around the variable.
I will create a Pull Request for it. It would be great if you could merge it afterwards.

Greetings, Thomas

Edit: Added reference to Pull Request https://github.com/MonsantoCo/etcd-aws-cluster/pull/19

**Comment by thomaspeitz** [comment]
https://github.com/MonsantoCo/etcd-aws-cluster/pull/21 - Created a new Pull Request

**Comment by tjcorr** [comment]
fixed by #21
