### ISSUE TITLE
Port settings broken because of merge conflict

### ISSUE THREAD

**Issue by dlipovetsky** [MonsantoCo/etcd-aws-cluster#28]
The client/server port settings introduced in https://github.com/MonsantoCo/etcd-aws-cluster/commit/f3b55e58171f3d7ef8d19e09dc2cdf9b987259ca were subsequently clobbered by https://github.com/MonsantoCo/etcd-aws-cluster/commit/ea5bb278c30387ec23845ccbb52dd55d22a06c4a

See line [57](https://github.com/MonsantoCo/etcd-aws-cluster/commit/ea5bb278c30387ec23845ccbb52dd55d22a06c4a#diff-de933a874abb449dade74b0f7f830a5dL57) and line [156](https://github.com/MonsantoCo/etcd-aws-cluster/commit/ea5bb278c30387ec23845ccbb52dd55d22a06c4a#diff-de933a874abb449dade74b0f7f830a5dL156) in the latter change. Instead of referencing bash variables, the use hard-coded port numbers.

**Comment by tjcorr** [comment]
good catch, I'll patch that right away

**Comment by dlipovetsky** [comment]
Sure. I was going to submit a PR, but I think you've beat me to it :)

**Comment by tjcorr** [comment]
looks like there is another spot too: https://github.com/MonsantoCo/etcd-aws-cluster/blob/master/etcd-aws-cluster#L147

**Comment by dlipovetsky** [comment]
You're right, my description missed that. For what's it worth, I submitted a PR: https://github.com/MonsantoCo/etcd-aws-cluster/pull/29

**Comment by tjcorr** [comment]
closed by #29
