### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by scivey** [MonsantoCo/etcd-aws-cluster#5]
So, just a quick question on the licensing terms of this project.

I'm currently running a regular etcd cluster inside of a VPC on AWS.  I'd like to spin up a new VPC for a trial run of etcd-aws-cluster.

The issue is that I'd like to link the two VPCs for centralized log management / monitoring / etc.  I'm concerned that this transfer of packets may constitute a kind of digital "cross pollination" which could result in my losing all legal rights to the existing cluster.

Is this something I should be concerned about? 
Please advise.

**Comment by ddgenome** [comment]
No.
